Bugfix: Handling of missing xz utils

diff --git a/bin/cb b/bin/cb
--- a/bin/cb
+++ b/bin/cb
@@ -1209,7 +1209,15 @@ installCb() {
 							[ -z "${i%%*.tar}" ] && CMD="tar $CB_TAR_PARAM -xf $i 2>&1" && TOPDIR_CMD="tar -tvf $i | head -n1 | awk '{print \$6}' | sed 's/\/\$//g'"
 							[ -z "${i%%*.tar.gz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i 2>&1" && TOPDIR_CMD="tar -ztvf $i | head -n1 | awk '{print \$6}' | sed 's/\/\$//g'"
 							[ -z "${i%%*.tgz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i 2>&1" && TOPDIR_CMD="tar -ztvf $i | head -n1 | awk '{print \$6}' | sed 's/\/\$//g'"
-							[ -z "${i%%*.xz}" ] && CMD="rm ${i%*.xz} > /dev/null 2>&1; xz $CB_XZ_PARAM --decompress $i 2>&1 && tar $CB_TAR_PARAM -xf ${i%*.xz} 2>&1; rm ${i%*.xz} > /dev/null 2>&1" && TOPDIR_CMD="tar -Jtvf $i | head -n1 | awk '{print \$6}' | sed 's/\/\$//g'"
+							if [ -z "${i%%*.xz}" ]; then
+								if ! [ -n "$(existBinary xz)" ]; then
+									CMD="echo \"${CB_LINEHEADER}Missing package xz (xz-utils), please install it before you continue!\">&2; false"
+									TOPDIR_CMD="true; echo \"ok\""
+								else
+									CMD="rm ${i%*.xz} > /dev/null 2>&1; xz $CB_XZ_PARAM --decompress $i 2>&1 && tar $CB_TAR_PARAM -xf ${i%*.xz} 2>&1; rm ${i%*.xz} > /dev/null 2>&1" 
+									TOPDIR_CMD="tar -Jtvf $i | head -n1 | awk '{print \$6}' | sed 's/\/\$//g'"
+								fi
+							fi
 						fi
 
 						if [ -n "$CMD" ]; then
diff --git a/bin/cb-install b/bin/cb-install
--- a/bin/cb-install
+++ b/bin/cb-install
@@ -175,6 +175,7 @@ installationSuccess() {
 		echo "${CB_LINEHEADER}Please re-login $msgInfo, before you start."
 		[ -n "$(existBinary unzip)" ] || echo "${CB_LINEHEADER}Missing package unzip, please install it before you continue!"
 		[ -n "$(existBinary find)" ] || echo "${CB_LINEHEADER}Missing package find, please install it before you continue!"
+		#[ -n "$(existBinary xz)" ] || echo "${CB_LINEHEADER}Missing package xz, please install it before you continue!"
 		echo "$CB_LINE"
 		echo ""
 	fi
