Bugfix

diff --git a/bin/cb b/bin/cb
--- a/bin/cb
+++ b/bin/cb
@@ -71,7 +71,7 @@ CB_INSTALL_OVERWRITE_DIST=$CB_INSTALL_OVERWRITE
 CB_PROJECT_JAVA_VERSION_FILE=".java-version"
 CB_JAVA_VERSION_FILE=".cb-java-version"
 rm -f "$CB_JAVA_VERSION_FILE" >/dev/null 2>&1
-[ -z "$CB_DEVTOOLS" ] && CB_DEVTOOLS=$(cd "$CB_HOME"/..; echo "$PWD") && export CB_DEVTOOLS
+[ -z "$CB_DEVTOOLS" ] && CB_DEVTOOLS=$(cd "$CB_HOME"/.. 2>/dev/null; echo "$PWD") && export CB_DEVTOOLS
 [ "$CB_OS" = "cygwin" ] && CB_DEVTOOLS=$(cygpath "$CB_DEVTOOLS")
 #[ -z "$(echo $CB_OS | sed 's/cygwin.*//')" ] && CLASSSEP=";" || CLASSSEP=":"
 
@@ -130,8 +130,8 @@ printVersion() {
 printPackages() {
 	readVersion
 	printVersion
-	#echo "available modules:"
 	packages=$(cd $CB_HOME/bin/packages && find . -type f -name "*.sh" | awk -F/ '{print "  "$2}')
+	echo "  cb"
 	echo "$packages"
 	echo "$CB_LINE"
 }
@@ -592,10 +592,14 @@ downloadPackage() {
 					[ $errorCode -ne 0 ] && echo "${CB_LINEHEADER}Error occured by download, give up!" | tee -a "$CB_LOGFILE"
 					[ $errorCode -ne 0 ] && echo "${CB_LINEHEADER}Call: $CB_LAST_CMD" | tee -a "$CB_LOGFILE"
 				fi
-				
+
 				# in case it is zero size we delete it
 				if [ -r "$CB_DEV_REPOSITORY/$CB_PACKAGE_DOWNLOAD_NAME" ]; then 
-					[ $(stat -c %s $CB_DEV_REPOSITORY/$CB_PACKAGE_DOWNLOAD_NAME) -eq 0 ] && rm -rf "$CB_DEV_REPOSITORY/$CB_PACKAGE_DOWNLOAD_NAME" >/dev/null 2>&1
+					if [ $(stat -c %s $CB_DEV_REPOSITORY/$CB_PACKAGE_DOWNLOAD_NAME) -lt 1000 ]; then
+						echo "${CB_LINEHEADER}Invalid package $CB_PACKAGE_NAME $CB_PACKAGE_VERSION, give up!" | tee -a "$CB_LOGFILE"
+						rm -rf "$CB_DEV_REPOSITORY/$CB_PACKAGE_DOWNLOAD_NAME" >/dev/null 2>&1
+						errorCode=1
+					fi
 				fi
 			fi
 		fi
@@ -613,6 +617,7 @@ installCb() {
 	DATEFORMAT="date '+%d.%m.%Y %H:%M:%S'"
 	USER_FRIENDLY_FULLTIMESTAMP=$(eval "$DATEFORMAT")
 	FULLTIMESTAMP=$(date '+%Y%m%d-%H%M%S')
+	errorCode=
 
 	# custom setting script
 	[ -n "$CB_CUSTOM_SETTING_SCRIPT" ] && eval ". $CB_CUSTOM_SETTING_SCRIPT install-start $*" 2>/dev/null
@@ -652,6 +657,10 @@ installCb() {
 	elif [ "$1" = "pkg" ]; then
 		CB_PKG_FILTER="*.zip" 
 		CB_PKG_FILTER_WILDCARD="true"
+	elif [ "$1" = "cb" ]; then
+		CB_PKG_FILTER=cb
+		CB_PKG_FILTER_WILDCARD=
+		CB_PACKAGE_DEST_VERSION_NAME=
 	else
 		CB_PKG_FILTER=
 		CB_PKG_FILTER_WILDCARD="false"
@@ -691,60 +700,74 @@ installCb() {
 		# custom setting script
 		[ -n "$CB_CUSTOM_SETTING_SCRIPT" ] && eval ". $CB_CUSTOM_SETTING_SCRIPT install-package-end $*" 2>/dev/null
 	else
-		downloadPackage "$1" "$2"
-		[ -n "$CB_PACKAGE_DOWNLOAD_NAME" ] && CB_PKG_FILTER=$CB_PACKAGE_DOWNLOAD_NAME 
+		if [ "$CB_PKG_FILTER" = "cb" ]; then
+			if [ "$CB_INSTALL_SILENT" = "false" ] ; then
+				[ -z "$2" ] && echo "${CB_LINEHEADER}Install newest cb version..." || echo "${CB_LINEHEADER}Install cb version $2..."
+			fi
+
+			[ "$CB_INSTALL_OVERWRITE_DIST" = "true" ] && eval "${CB_SCRIPT_PATH}/cb-install --force --silent $2"
+			[ "$CB_INSTALL_OVERWRITE_DIST" = "false" ] && eval "${CB_SCRIPT_PATH}/cb-install --silent $2"
+		else
+			downloadPackage "$1" "$2"
+			[ -n "$CB_PACKAGE_DOWNLOAD_NAME" ] && CB_PKG_FILTER=$CB_PACKAGE_DOWNLOAD_NAME 
+		fi
 	fi
 	
-	CB_TAR_PARAM="-k"
-	CB_UNZIP_PARAM="-n"
-	CB_XZ_PARAM="-k"
-	[ "$CB_INSTALL_OVERWRITE_DIST" = "true" ] && CB_UNZIP_PARAM="-o" && CB_TAR_PARAM="--overwrite" && CB_XZ_PARAM="-f"
-	[ -n "$CB_PACKAGE_DEST_VERSION_NAME" ] && mkdir -p $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME >/dev/null 2>&1 && CB_UNZIP_PARAM="$CB_UNZIP_PARAM -d $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME" && CB_TAR_PARAM="-C $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME"
-	
-	# extract
-	# custom setting script
-	[ -n "$CB_CUSTOM_SETTING_SCRIPT" ] && eval ". $CB_CUSTOM_SETTING_SCRIPT extract-archive-start $*" 2>/dev/null
+	if [ -z "$errorCode" ] || [ "$errorCode" -eq 0 ]; then	
+		#CB_TAR_PARAM="-k"
+		CB_TAR_PARAM=""
+		CB_UNZIP_PARAM="-n"
+		CB_XZ_PARAM="-k"
+		[ "$CB_INSTALL_OVERWRITE_DIST" = "true" ] && CB_UNZIP_PARAM="-o" && CB_TAR_PARAM="--overwrite" && CB_XZ_PARAM="-f"
+		[ -n "$CB_PACKAGE_DEST_VERSION_NAME" ] && mkdir -p $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME >/dev/null 2>&1 && CB_UNZIP_PARAM="$CB_UNZIP_PARAM -d $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME" && CB_TAR_PARAM="-C $CB_DEVTOOLS/$CB_PACKAGE_DEST_VERSION_NAME"
+		
+		# extract
+		# custom setting script
+		[ -n "$CB_CUSTOM_SETTING_SCRIPT" ] && eval ". $CB_CUSTOM_SETTING_SCRIPT extract-archive-start $*" 2>/dev/null
 
-	if [ -n "$CB_PKG_FILTER" ]; then
-		#[ "$CB_PKG_FILTER_WILDCARD" == "true" ] && 
-		echo "$CB_LINE" >> "$CB_LOGFILE"
-		echo "${CB_LINEHEADER}Extract $CB_PKG_FILTER in $CB_DEVTOOLS..." | tee -a "$CB_LOGFILE"
-		for i in $(ls -1 "$CB_DEV_REPOSITORY/$CB_PKG_FILTER" 2>/dev/null)
-		do
-			echo "${CB_LINEHEADER}Extract package $i" >> "$CB_LOGFILE"
+		if [ -n "$CB_PKG_FILTER" ]; then
+			if [ -n "$CB_PKG_FILTER_WILDCARD" ]; then
+				#[ "$CB_PKG_FILTER_WILDCARD" == "true" ] && 
+				[ "$CB_INSTALL_SILENT" = "false" ] && echo "$CB_LINE" >> "$CB_LOGFILE"
+				[ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Extract $CB_PKG_FILTER in $CB_DEVTOOLS..." | tee -a "$CB_LOGFILE"
+				for i in $(ls -1 "$CB_DEV_REPOSITORY/$CB_PKG_FILTER" 2>/dev/null)
+				do
+					[ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Extract package $i" >> "$CB_LOGFILE"
 
-			if [ -z "${i%%*.zip}" ]; then
-				if ! which unzip >/dev/null 2>&1; then
-					echo "${CB_LINEHEADER}Could not find unzip, please install unzip!"
-					CMD=""
-				else
-					[ -z "${i%%*.zip}" ] && CMD="unzip $CB_UNZIP_PARAM $i"
-				fi				
-			elif [ -z "${i%%*.exe}" ]; then
-				[ "$CB_OS" = "cygwin" ] && eval $i >> "$CB_LOGFILE"
-			elif [ -z "${i%%*.sh}" ]; then
-				eval $i >> "$CB_LOGFILE"
-			else			
-				[ -z "${i%%*.tar}" ] && CMD="tar $CB_TAR_PARAM -xf $i"
-				[ -z "${i%%*.tar.gz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i"
-				[ -z "${i%%*.tgz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i"
-				[ -z "${i%%*.xz}" ] && CMD="xz $CB_XZ_PARAM --decompress $i"
+					if [ -z "${i%%*.zip}" ]; then
+						if ! which unzip >/dev/null 2>&1; then
+							echo "${CB_LINEHEADER}Could not find unzip, please install unzip!"
+							CMD=""
+						else
+							[ -z "${i%%*.zip}" ] && CMD="unzip $CB_UNZIP_PARAM $i"
+						fi				
+					elif [ -z "${i%%*.exe}" ]; then
+						[ "$CB_OS" = "cygwin" ] && eval "cmd /c $(cygpath --windows $i | sed 's/\\/\\\\/g')" >> "$CB_LOGFILE"
+					elif [ -z "${i%%*.sh}" ]; then
+						eval $i >> "$CB_LOGFILE"
+					else			
+						[ -z "${i%%*.tar}" ] && CMD="tar $CB_TAR_PARAM -xf $i 2>&1"
+						[ -z "${i%%*.tar.gz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i 2>&1"
+						[ -z "${i%%*.tgz}" ] && CMD="tar $CB_TAR_PARAM -zxf $i 2>&1"
+						[ -z "${i%%*.xz}" ] && CMD="xz $CB_XZ_PARAM --decompress $i 2>&1"
+					fi
+					
+					if [ -n "$CMD" ]; then
+						CB_INSTALL_ERRORFILE=$CB_LOGS/$FULLTIMESTAMP-$CB_USER-error.log
+						if ! eval "cd $CB_DEVTOOLS && $CMD" 2>"$CB_INSTALL_ERRORFILE" >> "$CB_LOGFILE"; then 
+							echo "${CB_LINEHEADER}Could not extract $i:"
+							cat "$CB_INSTALL_ERRORFILE"
+						fi
+						rm -f "$CB_INSTALL_ERRORFILE" >/dev/null 2>&1
+					fi
+				done
+				[ "$CB_INSTALL_SILENT" = "false" ] && echo "$CB_LINE" >> "$CB_LOGFILE"
 			fi
-			
-			if [ -n "$CMD" ]; then
-				CB_INSTALL_ERRORFILE=$CB_LOGS/$FULLTIMESTAMP-$CB_USER-error.log
-				if ! eval "cd $CB_DEVTOOLS && $CMD 2>$CB_INSTALL_ERRORFILE" >> "$CB_LOGFILE"; then 
-					echo "${CB_LINEHEADER}Could not extract $i:"
-					cat "$CB_INSTALL_ERRORFILE"
-				fi
-				rm -f "$CB_INSTALL_ERRORFILE" >/dev/null 2>&1
-			fi
-		done
-		echo "$CB_LINE" >> "$CB_LOGFILE"
-	else
-		echo "${CB_LINEHEADER}No package found $CB_PACKAGE_VERSION_NAME ($CB_PKG_FILTER)"
+		else
+			[ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}No package found $CB_PACKAGE_VERSION_NAME ($CB_PKG_FILTER)"
+		fi
 	fi
-
+	
 	# custom setting script
 	[ -n "$CB_CUSTOM_SETTING_SCRIPT" ] && eval ". $CB_CUSTOM_SETTING_SCRIPT extract-archive-end $*" 2>/dev/null
 
