Finalzize version 1.1.0: graalvm support, documentation, nushell support

diff --git a/bin/cb b/bin/cb
--- a/bin/cb
+++ b/bin/cb
@@ -24,7 +24,7 @@
 #########################################################################
 
 
-CB_LINE="----------------------------------------------------------------------------------------"
+CB_LINE="------------------------------------------------------------------------------------------------------------------------"
 CB_LINEHEADER=".: "
 PN=$(basename "$0" 2>/dev/null)
 PN_FULL="$0"
@@ -157,16 +157,26 @@ endWithError() {
 	exit 1
 }
 
+# detect --setenv early so we can return (instead of exit) from a sourced script on fatal errors
+CB_SETENV_ONLY=""
+CB_NUSHELL=""
+for arg in "$@"; do
+	[ "$arg" = "--setenv" ] && CB_SETENV_ONLY=true
+	[ "$arg" = "--nushell" ] && CB_NUSHELL=true
+done
+
 if [ -z "$CB_HOME" ]; then
 	echo "$CB_LINE"
 	echo "${CB_LINEHEADER}Missing CB_HOME environment variable, please install with the cb-install."
 	echo "$CB_LINE"
+	[ "$CB_SETENV_ONLY" = "true" ] &&return 1 2>/dev/null || exit 1
 	endWithError
 fi
 if ! [ -n "$(existBinary find)" ]; then
 	echo "$CB_LINE"
 	echo "${CB_LINEHEADER}Missing package find, please install it before you continue."
 	echo "$CB_LINE"
+    [ "$CB_SETENV_ONLY" = "true" ] && return 1 2>/dev/null || exit 1
 	endWithError
 fi
 
@@ -456,6 +466,7 @@ printUsage() {
 	echo " -exp, --explore      Starts the file explorer with the current path."
 	echo " --update             Updates the custom config and can be combined with force."
 	echo " --setenv             Set all internal used environment variables."
+	echo " --nushell            When used with --setenv, output Nushell-compatible syntax."
 	echo ""
 	echo "Environment variable:"
 	echo " CB_DEVTOOLS          Defines the devtools directory, default \$HOME/devtools."
@@ -467,7 +478,7 @@ printUsage() {
 	echo "Customizing:"
 	echo " CB_CUSTOM_SETTING    The common build is flexible. You can define a script which"
 	echo "                      that is called as a hook for all operations. You can find an"
-	echo "                      example script in \$CB_HOME/bin/sample/cb-custom-sample.sh"
+	echo "                      example script in \$CB_HOME/docs/sample/cb-custom-sample.sh"
 	echo " CB_CUSTOM_CONFIG     For complete customizing of the common build you can create"
 	echo "                      a custom config project. This can be done by cb --new (select"	
 	echo "                      Common Config Home project). After customizing (see further "
@@ -600,43 +611,49 @@ setCBEnv() {
 		CB_NODE_HOME=$CB_CURRENT_PATH/node && NODE_HOME=$CB_NODE_HOME
 		[ -d "$CB_NODE_HOME/bin" ] && CB_NODE_BIN="$CB_NODE_HOME/bin" || CB_NODE_BIN="$CB_NODE_HOME"
 		[ -z "$(echo $PATH | grep $NODE_HOME)" ] && PATH="$CB_NODE_BIN:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add node to path ($CB_NODE_BIN)."
-		export CB_NODE_HOME NODE_HOME PATH
+		export NODE_HOME PATH
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/ant" ]; then
 		CB_ANT_HOME=$CB_CURRENT_PATH/ant && ANT_HOME=$CB_ANT_HOME
 		[ -z "$(echo $PATH | grep $ANT_HOME/bin)" ] && PATH="$ANT_HOME/bin:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add ant to path ($ANT_HOME/bin)."
-		export CB_ANT_HOME ANT_HOME PATH
+		export ANT_HOME PATH
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/maven" ]; then
 		CB_MAVEN_HOME=$CB_CURRENT_PATH/maven && MAVEN_HOME=$CB_MAVEN_HOME
 		[ -z "$(echo $PATH | grep $MAVEN_HOME/bin)" ] && PATH="$MAVEN_HOME/bin:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add maven to path ($MAVEN_HOME/bin)."
-		export CB_MAVEN_HOME MAVEN_HOME PATH
+		export MAVEN_HOME PATH
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/gradle" ]; then
 		CB_GRADLE_HOME=$CB_CURRENT_PATH/gradle && GRADLE_HOME=$CB_GRADLE_HOME
 		[ -z "$(echo $PATH | grep $GRADLE_HOME/bin)" ] && PATH="$GRADLE_HOME/bin:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add gradle to path ($GRADLE_HOME/bin)."
-		export CB_GRADLE_HOME GRADLE_HOME PATH
+		export GRADLE_HOME PATH
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/java" ]; then
 		CB_JAVA_HOME=$CB_CURRENT_PATH/java && JAVA_HOME=$CB_JAVA_HOME
 		[ -z "$(echo $PATH | grep $JAVA_HOME/bin)" ] && PATH="$JAVA_HOME/bin:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add java to path ($JAVA_HOME/bin)."
-		export CB_JAVA_HOME JAVA_HOME PATH
+		export JAVA_HOME PATH
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/graalvm" ]; then
+		[ -z "$GRAALVM_HOME" ] && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Set graalvm home (GRAALVM_HOME=$CB_CURRENT_PATH/graalvm)."
+		CB_GRAALVM_HOME=$CB_CURRENT_PATH/graalvm && GRAALVM_HOME=$CB_GRAALVM_HOME
+		export GRAALVM_HOME
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/python" ]; then
 		CB_PYTHON_HOME=$CB_CURRENT_PATH/python && PYTHON_HOME=$CB_PYTHON_HOME
 		[ -z "$(echo $PATH | grep $PYTHON_HOME)" ] && PATH="$PYTHON_HOME:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add python to path ($PYTHON_HOME)."
-		export CB_PYTHON_HOME PYTHON_HOME PATH
+		export PYTHON_HOME PATH
 	fi
 
 	if [ -d "$CB_CURRENT_PATH/trivy" ]; then
 		CB_TRIVY_HOME=$CB_CURRENT_PATH/trivy && TRIVY_HOME=$CB_TRIVY_HOME
 		[ -z "$(echo $PATH | grep $TRIVY_HOME)" ] && PATH="$TRIVY_HOME:$PATH" && [ "$CB_INSTALL_SILENT" = "false" ] && echo "${CB_LINEHEADER}Add trivy to path ($TRIVY_HOME)."
-		export CB_TRIVY_HOME TRIVY_HOME PATH
+		export TRIVY_HOME PATH
 	fi
 
 	# custom setting script
@@ -648,6 +665,63 @@ setCBEnv() {
 	unset CB_LINEHEADER
 	unset CB_CUSTOM_SETTING_SCRIPT
 	unset CB_SETENV_ONLY
+	unset CB_NUSHELL
+}
+
+
+#########################################################################
+# setCBEnvNushell: output Nushell-compatible environment variable syntax
+#########################################################################
+setCBEnvNushell() {
+	shift
+	[ "$1" = "--silent" ] && shift
+	[ "$1" = "--nushell" ] && shift
+
+	if [ -d "$CB_CURRENT_PATH/git" ]; then
+		CB_GIT_BIN="$CB_CURRENT_PATH/git/bin"
+		echo "\$env.GIT_HOME = '$CB_CURRENT_PATH/git'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_GIT_BIN')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/node" ]; then
+		[ -d "$CB_CURRENT_PATH/node/bin" ] && CB_NODE_BIN="$CB_CURRENT_PATH/node/bin" || CB_NODE_BIN="$CB_CURRENT_PATH/node"
+		echo "\$env.NODE_HOME = '$CB_CURRENT_PATH/node'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_NODE_BIN')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/ant" ]; then
+		echo "\$env.ANT_HOME = '$CB_CURRENT_PATH/ant'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/ant/bin')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/maven" ]; then
+		echo "\$env.MAVEN_HOME = '$CB_CURRENT_PATH/maven'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/maven/bin')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/gradle" ]; then
+		echo "\$env.GRADLE_HOME = '$CB_CURRENT_PATH/gradle'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/gradle/bin')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/java" ]; then
+		echo "\$env.JAVA_HOME = '$CB_CURRENT_PATH/java'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/java/bin')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/graalvm" ]; then
+		echo "\$env.GRAALVM_HOME = '$CB_CURRENT_PATH/graalvm'"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/python" ]; then
+		echo "\$env.PYTHON_HOME = '$CB_CURRENT_PATH/python'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/python')"
+	fi
+
+	if [ -d "$CB_CURRENT_PATH/trivy" ]; then
+		echo "\$env.TRIVY_HOME = '$CB_CURRENT_PATH/trivy'"
+		echo "\$env.PATH = (\$env.PATH | prepend '$CB_CURRENT_PATH/trivy')"
+	fi
 }
 
 
@@ -844,7 +918,11 @@ verifyConfiguration() {
 	    GRADLE_PROPERTIES="$CB_WORKING_PATH/gradle.properties"
 		if [ -r "$GRADLE_PROPERTIES" ] && [ $(grep '\-XX:MaxPermSize=' "$GRADLE_PROPERTIES" | wc -l) -gt 0 ]; then
 			echo "${CB_LINEHEADER}Update ${GRADLE_PROPERTIES}..."
+			if [ "$CB_OS" = "mac" ]; then
+			sed -i '' 's/\-XX:MaxPermSize=/\-XX:MaxMetaspaceSize=/' "$GRADLE_PROPERTIES"
+		else
 			sed -i 's/\-XX:MaxPermSize=/\-XX:MaxMetaspaceSize=/' "$GRADLE_PROPERTIES"
+		fi
 			CB_BUILD_UPDATE="true"
 			export CB_BUILD_UPDATE
 		fi
@@ -1498,7 +1576,8 @@ do
 		-exp)		shift; exploreProject; exit 0;;
 		--explore)	shift; exploreProject; exit 0;;
 		--packages)	shift; printPackages "$@"; exit 0;;
-		--setenv)	CB_EXECUTE_BUILD=false; setCBEnv "$@"; unset errorCode;;
+		--nushell)	CB_NUSHELL=true;;
+		--setenv)	CB_EXECUTE_BUILD=false; if [ "$CB_NUSHELL" = "true" ]; then setCBEnvNushell "$@"; else setCBEnv "$@"; fi; CB_SETENV_ONLY=true; break;;
 		--install)	shift; installCb "$@"; [ -n "$errorCode" ] && exit $errorCode || exit 0;;
 		--java)		shift && echo $1 > $CB_JAVA_VERSION_FILE;;
 		--update)	updateCustomConfig; exit 0;;
@@ -1509,6 +1588,12 @@ done
 
 if [ -n "$CB_EXECUTE_BUILD" ] && [ "$CB_EXECUTE_BUILD" = "true" ]; then
 	commonBuild "$CB_PARAMETERS"
+fi
+
+# on --setenv: clean up all CB_* internal variables before returning (do not clean CB_HOME)
+if [ "$CB_SETENV_ONLY" = "true" ]; then
+	unset errorCode CB_START_TIMESTAMP CB_END_TIMESTAMP CB_VERBOSE CB_MACHINE CB_LINE CB_TEMP CB_LINEHEADER CB_OS CB_SETENV_ONLY CB_NUSHELL CB_WORKING_PATH CB_SCRIPT_PATH CB_INSTALL_SILENT CB_EXECUTE_BUILD CB_PARAMETERS CB_CURRENT_PATH CB_CUSTOM_SETTING_SCRIPT CB_NODE_HOME CB_NODE_BIN CB_ANT_HOME CB_MAVEN_HOME CB_GRADLE_HOME CB_JAVA_HOME CB_GRAALVM_HOME CB_PYTHON_HOME CB_TRIVY_HOME CB_INSTALL_USER_COMMIT CB_USER CB_PACKAGE_URL CB_PACKAGE_PASSWORD CB_DEVTOOLS_JAVA_PREFIX CB_INSTALL_OVERWRITE CB_CUSTOM_CONFIG_FILENAME OS_HOME
+	return 0 2>/dev/null || exit 0
 fi
 
 setTitle "$PWD"
diff --git a/bin/cb-clean-files b/bin/cb-clean-files
--- a/bin/cb-clean-files
+++ b/bin/cb-clean-files
@@ -4,6 +4,11 @@
 #
 # cb-clean-files
 #
+# Deletes regular files older than N days from a single directory
+# (non-recursive, top level only), filtered by an optional glob pattern.
+# Rejects dangerous target paths (/, $HOME, /usr, /etc, ...). Supports
+# --dry-run and --silent modes, reports how many files were deleted.
+#
 # Copyright by toolarium, all rights reserved.
 #
 # This file is part of the toolarium common-build.
@@ -30,19 +35,8 @@ export CB_TEMP
 CLEAN_PATH="$CB_TEMP"
 CLEAN_PATTERN="*"
 CLEAN_DAYS=1
-
-
-#########################################################################
-# Parse a json output an element
-#########################################################################
-parseJson() {
-	processed=$(catOut "$@")
-	for i in $(echo "$nameFilter" | tr "." "\n"); do
-		[ "#" = "$i" ] && tagElementFilter="" || tagElementFilter="$i"
-		processed="$(echo $processed | cutJsonElement)"
-	done
-	echo "$processed"
-}
+CB_SILENT=false
+CB_DRY_RUN=false
 
 
 #########################################################################
@@ -50,19 +44,26 @@ parseJson() {
 #########################################################################
 printUsage() {
 	echo "$PN - clean files"
-	echo "usage: $PN [OPTION]"	
+	echo "usage: $PN [OPTION]"
+	echo ""
+	echo "Deletes regular files (NOT directories) older than N days from the"
+	echo "top level of a single directory, filtered by an optional glob pattern."
+	echo "Non-recursive: subdirectories are never entered and never removed."
+	echo "Dangerous target paths (/, \$HOME, /usr, /etc, ...) are refused."
 	echo ""
 	echo "Overview of the available OPTIONs:"
 	echo " -h, --help           Show this help message."
-	echo " --path path          Defines the path, default \$CB_TEMP"
-	echo " --pattern pattern    Defines the file pattern, default $CLEAN_PATTERN"
-	echo " --days days          The number of days back to delete, default $CLEAN_DAYS"
+	echo " --silent             Suppress informational output."
+	echo " --dry-run            List matching files without deleting them."
+	echo " --path path          Target directory (default \$CB_TEMP). The directory itself is never removed."
+	echo " --pattern pattern    File name glob, default $CLEAN_PATTERN"
+	echo " --days days          Delete files with mtime older than N days, default $CLEAN_DAYS"
 	echo ""
 	echo "Examples:"
-	echo " Delete cb temp files:"
+	echo " Delete cb temp files older than 1 day:"
 	echo " cb-clean-files"
 	echo ""
-	echo " Delete gradle worrker files:"
+	echo " Delete gradle worker files in /tmp:"
 	echo " cb-clean-files --path /tmp --pattern gradle-worker*"
 }
 
@@ -70,25 +71,48 @@ printUsage() {
 #########################################################################
 # main
 #########################################################################
-parseContent="false"
-returnValue=false
 while [ $# -gt 0 ]; do
     case "$1" in
 		-h) 			printUsage; exit 0;;
 		--help) 		printUsage; exit 0;;
-		--path) 		shift; CLEAN_PATH="$1";;
-		--pattern) 		shift; CLEAN_PATTERN="$1";;
-		--days) 		shift; CLEAN_DAYS="$1";;
+		--silent)		CB_SILENT=true;;
+		--dry-run)		CB_DRY_RUN=true;;
+		--path) 		shift; [ -z "$1" ] && echo "Missing value for --path"; CLEAN_PATH="$1";;
+		--pattern) 		shift; [ -z "$1" ] && echo "Missing value for --pattern"; CLEAN_PATTERN="$1";;
+		--days) 		shift; [ -z "$1" ] && echo "Missing value for --days"; CLEAN_DAYS="$1";;
 		*) 				echo "Invalid parameter: $1"; echo ""; printUsage; exit 1;;
     esac
 	shift
 done
 
-if [ -r "$CLEAN_PATH" ]; then
-	echo ".: Clean in [$CLEAN_PATH] with pattern [$CLEAN_PATTERN] which are older than $CLEAN_DAYS day(s)..."
-	find "$CLEAN_PATH" -name "$CLEAN_PATTERN" -mtime $CLEAN_DAYS -exec rm -f 2>/dev/null {} \;
+# validate --days is a positive integer
+case "$CLEAN_DAYS" in
+	''|*[!0-9]*) echo ".: Invalid --days value [$CLEAN_DAYS], must be a non-negative integer"; exit 1;;
+esac
+
+# validate --path is not empty or a dangerous root location
+CLEAN_PATH_ABS=$(cd "$CLEAN_PATH" 2>/dev/null && pwd)
+if [ -z "$CLEAN_PATH_ABS" ]; then
+	[ "$CB_SILENT" = "false" ] && echo ".: Path $CLEAN_PATH don't exist"
+	exit 0
+fi
+case "$CLEAN_PATH_ABS" in
+	/|/bin|/boot|/dev|/etc|/home|/lib|/lib64|/opt|/proc|/root|/run|/sbin|/srv|/sys|/usr|/var|"$HOME")
+		echo ".: Refusing to clean dangerous path [$CLEAN_PATH_ABS]"; exit 1;;
+esac
+
+if [ -d "$CLEAN_PATH" ]; then
+	if [ "$CB_DRY_RUN" = "true" ]; then
+		[ "$CB_SILENT" = "false" ] && echo ".: [DRY-RUN] Would clean in [$CLEAN_PATH] with pattern [$CLEAN_PATTERN] which are older than $CLEAN_DAYS day(s)..."
+		deletedCount=$(find "$CLEAN_PATH" -maxdepth 1 -type f -name "$CLEAN_PATTERN" -mtime +$CLEAN_DAYS -print 2>/dev/null | wc -l)
+		[ "$CB_SILENT" = "false" ] && echo ".: [DRY-RUN] Would delete $deletedCount file(s)."
+	else
+		[ "$CB_SILENT" = "false" ] && echo ".: Clean in [$CLEAN_PATH] with pattern [$CLEAN_PATTERN] which are older than $CLEAN_DAYS day(s)..."
+		deletedCount=$(find "$CLEAN_PATH" -maxdepth 1 -type f -name "$CLEAN_PATTERN" -mtime +$CLEAN_DAYS -print -delete 2>/dev/null | wc -l)
+		[ "$CB_SILENT" = "false" ] && echo ".: Deleted $deletedCount file(s)."
+	fi
 else
-	echo ".: Path $CLEAN_PATH don't exist"
+	[ "$CB_SILENT" = "false" ] && echo ".: Path $CLEAN_PATH don't exist"
 fi
 
 
